package jellycompat

import (
	"context"
	"net/http"
	"net/http/httptest"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/Silo-Server/silo-server/internal/catalog"
	"github.com/Silo-Server/silo-server/internal/config"
	"github.com/Silo-Server/silo-server/internal/models"
)

// fakeCollectionPosters gives each profile its own collage of every
// collection without an uploaded poster, and records the access it was asked
// about.
type fakeCollectionPosters struct {
	collages map[string]catalog.CollectionPoster // "{collectionID}/{key}"
	byViewer map[string]string                   // profile ID -> collage key
	asked    []catalog.AccessFilter
}

func (f *fakeCollectionPosters) CollectionPosters(_ context.Context, collections []*models.LibraryCollection, access catalog.AccessFilter) map[string]catalog.CollectionPoster {
	f.asked = append(f.asked, access)
	out := map[string]catalog.CollectionPoster{}
	for _, c := range collections {
		if poster, ok := catalog.AssignedCollectionPoster(c); ok {
			out[c.ID] = poster
			continue
		}
		if poster, ok := f.collages[c.ID+"/"+f.byViewer[access.ProfileID]]; ok {
			out[c.ID] = poster
		}
	}
	return out
}

func (f *fakeCollectionPosters) CollectionCollage(_ context.Context, collectionID, key string) (catalog.CollectionPoster, bool, error) {
	poster, ok := f.collages[collectionID+"/"+key]
	return poster, ok, nil
}

func collagePoster(collectionID, key string) catalog.CollectionPoster {
	return catalog.CollectionPoster{
		Path:       "collection-images/" + collectionID + "/collage/original." + key + ".webp",
		CollageKey: key,
	}
}

func TestCollageImageTagNamesItsCollage(t *testing.T) {
	signer := newImageTagSigner("image-secret")
	codec := NewResourceIDCodec()
	routeID := codec.EncodeStringID(EncodedIDCollection, "101")
	const key = "0123456789abcdef"

	tag := collageImageTag(signer, routeID, key)
	if !regexp.MustCompile(`^[0-9a-f]{32}$`).MatchString(tag) || !strings.HasPrefix(tag, key) {
		t.Fatalf("tag = %q, want the key followed by 16 hex digits", tag)
	}
	for name, candidate := range map[string]string{"plain": tag, "proxy": compatImageProxyTag(tag)} {
		if got, ok := verifiedCollageImageTag(signer, routeID, candidate); !ok || got != key {
			t.Fatalf("%s tag verified as (%q, %v), want %q", name, got, ok, key)
		}
	}

	otherRoute := codec.EncodeStringID(EncodedIDCollection, "102")
	forgedKey := "fedcba9876543210" + tag[collageTagKeyLength:]
	plainTag := signer.Tag(imageTagSeed(routeID, "Primary", compatCardImageSize, "collection-images/101/poster/original.webp", "", time.Time{}), "")
	for name, tc := range map[string]struct{ routeID, tag string }{
		"another collection": {otherRoute, tag},
		"another key":        {routeID, forgedKey},
		"an ordinary tag":    {routeID, plainTag},
	} {
		if _, ok := verifiedCollageImageTag(signer, tc.routeID, tc.tag); ok {
			t.Fatalf("%s verified as a collage tag", name)
		}
	}
	if _, ok := verifiedCollageImageTag(nil, routeID, tag); ok {
		t.Fatal("a collage tag verified without a signing secret")
	}
}

func TestBoxSetListShowsEachViewerItsOwnCollage(t *testing.T) {
	collections := &fakeCollectionSource{collections: []*models.LibraryCollection{
		{ID: "101", LibraryID: 1, Title: "Collage", Visibility: "visible"},
		{ID: "102", LibraryID: 1, Title: "Uploaded", Visibility: "visible", PosterURL: "/images/collection-templates/x.jpg"},
		// A shared collage stored by an older server is never shown.
		{ID: "103", LibraryID: 1, Title: "Legacy", Visibility: "visible", PosterURL: "collection-images/103/poster/original.1.webp", PosterAutoGenerated: true},
	}}
	h := newCollectionsTestHandler(collections, []upstreamUserLibrary{{ID: 1, Name: "Movies", Type: "movies"}}, nil)
	h.mapper = newMapper(h.codec, &config.Config{Auth: config.AuthConfig{JWTSecret: "image-secret"}})
	h.posterPresigner = fakeLibraryPosterPresigner{url: "https://s3.example/collage.webp"}
	h.accessFilter = func(_ context.Context, _ int, profileID string) catalog.AccessFilter {
		return catalog.AccessFilter{ProfileID: profileID}
	}
	const viewerKey = "0123456789abcdef"
	posters := &fakeCollectionPosters{
		collages: map[string]catalog.CollectionPoster{"101/" + viewerKey: collagePoster("101", viewerKey)},
		byViewer: map[string]string{collectionsTestSession().ProfileID: viewerKey},
	}
	h.collectionPosters = posters

	result := performItemsRequest(t, h, "/Items?IncludeItemTypes=BoxSet&Recursive=true")
	tags := map[string]string{}
	for _, item := range result.Items {
		tags[item.Name] = item.ImageTags["Primary"]
	}

	routeID := h.codec.EncodeStringID(EncodedIDCollection, "101")
	if got, ok := verifiedCollageImageTag(h.mapper.imageTagSigner, routeID, tags["Collage"]); !ok || got != viewerKey {
		t.Fatalf("collage tag %q names (%q, %v), want the viewer's collage %q", tags["Collage"], got, ok, viewerKey)
	}
	if _, ok := h.images.LookupSized(routeID, "Primary", "", compatCardImageSize); ok {
		t.Fatal("a viewer's collage was cached for every viewer of the route")
	}
	if len(tags["Uploaded"]) != 16 {
		t.Fatalf("uploaded poster tag = %q, want an ordinary tag", tags["Uploaded"])
	}
	legacyRoute := h.codec.EncodeStringID(EncodedIDCollection, "103")
	wantLegacy := h.mapper.imageTagSigner.Tag(imageTagSeed(legacyRoute, "Primary", compatCardImageSize, generatedPosterSeed("Legacy"), "", time.Time{}), "")
	if tags["Legacy"] != wantLegacy {
		t.Fatalf("legacy collage tag = %q, want the generated title poster's %q", tags["Legacy"], wantLegacy)
	}
	if len(posters.asked) != 1 || posters.asked[0].ProfileID != collectionsTestSession().ProfileID {
		t.Fatalf("posters resolved for %+v, want one batch for the session's profile", posters.asked)
	}
}

func newCollageImagesHandler(collection *models.LibraryCollection, posters *fakeCollectionPosters) *ImagesHandler {
	return &ImagesHandler{
		codec:             NewResourceIDCodec(),
		content:           &librariesContentService{libraries: []upstreamUserLibrary{{ID: 1, Name: "Movies", Type: "movies"}}},
		images:            NewImageCache(time.Hour, time.Now),
		imageTags:         newImageTagSigner("image-secret"),
		posterSigner:      fakeLibraryPosterPresigner{url: "https://s3.example/collage.webp"},
		collections:       &fakeCollectionSource{collections: []*models.LibraryCollection{collection}},
		collectionPosters: posters,
		accessFilter: func(_ context.Context, _ int, profileID string) catalog.AccessFilter {
			return catalog.AccessFilter{ProfileID: profileID}
		},
	}
}

func serveCollageImage(h *ImagesHandler, routeID, tag string, session *Session) *httptest.ResponseRecorder {
	target := "/Items/" + routeID + "/Images/Primary"
	if tag != "" {
		target += "?tag=" + tag
	}
	req := httptest.NewRequest(http.MethodGet, target, nil)
	if session != nil {
		req = req.WithContext(context.WithValue(req.Context(), compatSessionKey, session))
	}
	req = withImageRouteParams(req, routeID, "Primary")
	rec := httptest.NewRecorder()
	h.HandleItemImage(rec, req)
	return rec
}

func TestServeCollectionImageServesTaggedCollageWithoutSession(t *testing.T) {
	collection := &models.LibraryCollection{ID: "101", LibraryID: 1, Title: "Collage", Visibility: "visible"}
	const key = "0123456789abcdef"
	h := newCollageImagesHandler(collection, &fakeCollectionPosters{
		collages: map[string]catalog.CollectionPoster{"101/" + key: collagePoster("101", key)},
	})
	routeID := h.codec.EncodeStringID(EncodedIDCollection, "101")

	rec := serveCollageImage(h, routeID, collageImageTag(h.imageTags, routeID, key), nil)
	if rec.Code != http.StatusFound || rec.Header().Get("Location") != "https://s3.example/collage.webp" {
		t.Fatalf("tagged collage: status %d location %q, want a redirect to the collage", rec.Code, rec.Header().Get("Location"))
	}

	// A signed tag for a collage that is gone falls back to the title poster.
	const goneKey = "fedcba9876543210"
	rec = serveCollageImage(h, routeID, collageImageTag(h.imageTags, routeID, goneKey), nil)
	if rec.Code != http.StatusOK || rec.Header().Get("Content-Type") != "image/png" {
		t.Fatalf("missing collage: status %d type %q, want the generated poster", rec.Code, rec.Header().Get("Content-Type"))
	}

	// A forged collage tag authorizes nothing.
	forged := goneKey + collageImageTag(h.imageTags, routeID, key)[collageTagKeyLength:]
	if rec := serveCollageImage(h, routeID, forged, nil); rec.Code != http.StatusNotFound {
		t.Fatalf("forged collage tag: status %d, want 404", rec.Code)
	}
}

func TestServeCollectionImageUntaggedGivesTheSessionItsCollage(t *testing.T) {
	collection := &models.LibraryCollection{ID: "101", LibraryID: 1, Title: "Collage", Visibility: "visible"}
	const key = "0123456789abcdef"
	session := collectionsTestSession()
	h := newCollageImagesHandler(collection, &fakeCollectionPosters{
		collages: map[string]catalog.CollectionPoster{"101/" + key: collagePoster("101", key)},
		byViewer: map[string]string{session.ProfileID: key},
	})
	routeID := h.codec.EncodeStringID(EncodedIDCollection, "101")

	rec := serveCollageImage(h, routeID, "", session)
	if rec.Code != http.StatusFound || rec.Header().Get("Location") != "https://s3.example/collage.webp" {
		t.Fatalf("status %d location %q, want a redirect to the viewer's collage", rec.Code, rec.Header().Get("Location"))
	}

	// A viewer without a built collage gets the title poster.
	other := &Session{StreamAppUserID: 2, ProfileID: "profile-2"}
	rec = serveCollageImage(h, routeID, "", other)
	if rec.Code != http.StatusOK || rec.Header().Get("Content-Type") != "image/png" {
		t.Fatalf("no collage: status %d type %q, want the generated poster", rec.Code, rec.Header().Get("Content-Type"))
	}
}

func TestServeCollectionImageNeverServesLegacySharedCollage(t *testing.T) {
	legacyPath := "collection-images/101/poster/original.1.webp"
	collection := &models.LibraryCollection{ID: "101", LibraryID: 1, Title: "Legacy", Visibility: "visible", PosterURL: legacyPath, PosterAutoGenerated: true}
	h := newCollageImagesHandler(collection, &fakeCollectionPosters{})
	routeID := h.codec.EncodeStringID(EncodedIDCollection, "101")

	oldTag := h.imageTags.Tag(imageTagSeed(routeID, "Primary", compatCardImageSize, legacyPath, "", time.Time{}), "")
	if rec := serveCollageImage(h, routeID, oldTag, nil); rec.Code != http.StatusNotFound {
		t.Fatalf("legacy tag: status %d, want 404", rec.Code)
	}
	rec := serveCollageImage(h, routeID, "", collectionsTestSession())
	if rec.Code != http.StatusOK || rec.Header().Get("Content-Type") != "image/png" {
		t.Fatalf("session request: status %d type %q, want the generated poster", rec.Code, rec.Header().Get("Content-Type"))
	}
}
