package catalog

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"runtime/debug"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/Silo-Server/silo-server/internal/collage"
	"github.com/Silo-Server/silo-server/internal/models"
)

// A server collection without an uploaded or template poster shows a collage
// of its members' posters. The members it shows depend on the viewer: each
// viewer sees the first members it can access, in collection order, so a
// restricted profile never sees the poster of a title it can't open (#1618).
//
// Each distinct set of source posters is one stored collage, shared by every
// viewer that selects the same posters. Its key is a hash of those posters, so
// a change to the members, their order, or their artwork selects a new collage
// rather than serving a stale one. library_collections.poster_url holds only
// uploaded and template posters.
const (
	// CollectionCollageSourceLimit is the most member posters one collage shows.
	CollectionCollageSourceLimit = 4

	// collectionCollageLayout versions how a collage is composed from its
	// sources. Changing the composition must change this value, so collages
	// already stored are rebuilt instead of reused.
	collectionCollageLayout = "collage-v1"

	// A collage in use is touched at most this often, so reads rarely write.
	collectionCollageTouchInterval = 24 * time.Hour
	// A collage nobody has read for this long is retired the next time a
	// collage of the same collection is built.
	collectionCollageUnusedAfter = 7 * 24 * time.Hour

	collageBuildConcurrency = 2
	collageBuildMaxPending  = 256
	collageBuildTimeout     = 2 * time.Minute
	// After a failed build, reads don't retry the same collage for this long.
	collageBuildRetryAfter = 10 * time.Minute
)

// ErrCollectionCollageBeingCollected reports that the artwork revision
// collector is deleting a collage's objects, so it can't be rebuilt yet.
var ErrCollectionCollageBeingCollected = errors.New("collection collage is being collected")

// CollectionPoster is the poster one viewer sees for a server collection.
type CollectionPoster struct {
	Path      string
	Thumbhash string
	// CollageKey names the viewer's collage. It is empty for an uploaded or
	// template poster, which every viewer shares.
	CollageKey string
}

// CollectionCollageRef names one stored collage of a collection.
type CollectionCollageRef struct {
	CollectionID string
	Key          string
}

// CollectionCollage is one stored collage.
type CollectionCollage struct {
	CollectionCollageRef
	Path       string
	Thumbhash  string
	LastUsedAt time.Time
}

// collectionUsesLiveQuery reports whether the catalog lists the collection's
// members from its query rather than its stored items, as
// resolveLibraryCollectionCursor decides. Such a collection has no collage.
func collectionUsesLiveQuery(c *models.LibraryCollection) bool {
	return IsLiveQueryType(c.CollectionType) || catalogCollectionUsesLiveQuery(c.QueryDefinition)
}

// CollectionCollageKey returns the key of the collage composed from sources,
// the member poster paths in the order the collage shows them.
func CollectionCollageKey(sources []string) string {
	sum := sha256.New()
	sum.Write([]byte(collectionCollageLayout))
	for _, source := range sources {
		sum.Write([]byte{0})
		sum.Write([]byte(source))
	}
	return hex.EncodeToString(sum.Sum(nil)[:8])
}

// AssignedCollectionPoster returns the collection's uploaded or template
// poster, which every viewer shares. A poster_url marked auto-generated is the
// shared collage older servers stored, which is never served.
func AssignedCollectionPoster(c *models.LibraryCollection) (CollectionPoster, bool) {
	if strings.TrimSpace(c.PosterURL) == "" || c.PosterAutoGenerated {
		return CollectionPoster{}, false
	}
	return CollectionPoster{Path: c.PosterURL, Thumbhash: c.PosterThumbhash}, true
}

// ListCollectionCollageSources returns, for each collection, the poster paths
// of up to CollectionCollageSourceLimit members the viewer can access, in
// collection order. It applies the same access predicates as the collection's
// member list, so a collage never shows a member that list leaves out.
// Collections with no such member are absent from the result.
func (r *LibraryCollectionRepository) ListCollectionCollageSources(ctx context.Context, collectionIDs []string, access AccessFilter) (map[string][]string, error) {
	sources := make(map[string][]string, len(collectionIDs))
	if len(collectionIDs) == 0 || (access.AllowedLibraryIDs != nil && len(access.AllowedLibraryIDs) == 0) {
		return sources, nil
	}
	// A repeated ID would repeat its rows and double its sources.
	ids := slices.Clone(collectionIDs)
	slices.Sort(ids)
	sql, args := buildCollectionCollageSourcesSQL(slices.Compact(ids), access)
	rows, err := r.pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, fmt.Errorf("listing collection collage sources: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var id, path string
		if err := rows.Scan(&id, &path); err != nil {
			return nil, fmt.Errorf("scanning collection collage source: %w", err)
		}
		sources[id] = append(sources[id], path)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating collection collage sources: %w", err)
	}
	return sources, nil
}

func buildCollectionCollageSourcesSQL(collectionIDs []string, access AccessFilter) (string, []any) {
	args := []any{collectionIDs, CollectionCollageSourceLimit}
	argIdx := 3
	var memberWhere strings.Builder
	for _, condition := range itemAccessConditions(access, &args, &argIdx) {
		memberWhere.WriteString("\n\t\t\t  AND " + condition)
	}
	return `
		SELECT c.id, src.poster_path
		FROM unnest($1::text[]) WITH ORDINALITY AS c(id, ord)
		CROSS JOIN LATERAL (
			SELECT mi.poster_path, lci.position, lci.source_rank, lci.media_item_id
			FROM library_collection_items lci
			JOIN media_items mi ON mi.content_id = lci.media_item_id
			WHERE lci.collection_id = c.id
			  AND mi.poster_path <> ''` + memberWhere.String() + `
			ORDER BY lci.position, lci.source_rank, lci.media_item_id
			LIMIT $2
		) src
		ORDER BY c.ord, src.position, src.source_rank, src.media_item_id`, args
}

// GetCollectionCollages returns the stored collages among refs.
func (r *LibraryCollectionRepository) GetCollectionCollages(ctx context.Context, refs []CollectionCollageRef) (map[CollectionCollageRef]CollectionCollage, error) {
	collages := make(map[CollectionCollageRef]CollectionCollage, len(refs))
	if len(refs) == 0 {
		return collages, nil
	}
	ids, keys := splitCollectionCollageRefs(refs)
	rows, err := r.pool.Query(ctx, `
		SELECT v.collection_id, v.variant_key, v.poster_path, v.poster_thumbhash, v.last_used_at
		FROM unnest($1::text[], $2::text[]) AS ref(collection_id, variant_key)
		JOIN library_collection_poster_variants v
		  ON v.collection_id = ref.collection_id AND v.variant_key = ref.variant_key
	`, ids, keys)
	if err != nil {
		return nil, fmt.Errorf("loading collection collages: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var c CollectionCollage
		if err := rows.Scan(&c.CollectionID, &c.Key, &c.Path, &c.Thumbhash, &c.LastUsedAt); err != nil {
			return nil, fmt.Errorf("scanning collection collage: %w", err)
		}
		collages[c.CollectionCollageRef] = c
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating collection collages: %w", err)
	}
	return collages, nil
}

// TouchCollectionCollages records that refs were just served.
func (r *LibraryCollectionRepository) TouchCollectionCollages(ctx context.Context, refs []CollectionCollageRef) error {
	if len(refs) == 0 {
		return nil
	}
	ids, keys := splitCollectionCollageRefs(refs)
	if _, err := r.pool.Exec(ctx, `
		UPDATE library_collection_poster_variants v
		SET last_used_at = NOW()
		FROM unnest($1::text[], $2::text[]) AS ref(collection_id, variant_key)
		WHERE v.collection_id = ref.collection_id AND v.variant_key = ref.variant_key
	`, ids, keys); err != nil {
		return fmt.Errorf("touching collection collages: %w", err)
	}
	return nil
}

// SaveCollectionCollage stores a built collage, replacing one with the same
// key, and in the same transaction releases the path's reservation in the
// artwork revision collector's queue: the row now protects the objects. It
// returns ErrLibraryCollectionNotFound when the collection is gone, leaving the
// reservation for the collector.
func (r *LibraryCollectionRepository) SaveCollectionCollage(ctx context.Context, c CollectionCollage) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning collection collage save: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	tag, err := tx.Exec(ctx, `
		INSERT INTO library_collection_poster_variants (collection_id, variant_key, poster_path, poster_thumbhash)
		SELECT $1, $2, $3, $4
		WHERE EXISTS (SELECT 1 FROM library_collections WHERE id = $1)
		ON CONFLICT (collection_id, variant_key) DO UPDATE
		SET poster_path = EXCLUDED.poster_path,
		    poster_thumbhash = EXCLUDED.poster_thumbhash,
		    last_used_at = NOW()
	`, c.CollectionID, c.Key, c.Path, c.Thumbhash)
	if err != nil {
		return fmt.Errorf("saving collection collage: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrLibraryCollectionNotFound
	}
	if _, err := tx.Exec(ctx, `
		DELETE FROM artwork_revision_gc_candidates
		WHERE original_path = $1 AND locked_at IS NULL
	`, c.Path); err != nil {
		return fmt.Errorf("releasing collection collage reservation: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("committing collection collage save: %w", err)
	}
	return nil
}

// RetireUnusedCollectionCollages deletes the collection's collages last
// served before cutoff and returns how many it deleted. The table's delete
// trigger hands their objects to the artwork revision collector in the same
// transaction.
func (r *LibraryCollectionRepository) RetireUnusedCollectionCollages(ctx context.Context, collectionID string, cutoff time.Time) (int, error) {
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM library_collection_poster_variants
		WHERE collection_id = $1 AND last_used_at < $2
	`, collectionID, cutoff)
	if err != nil {
		return 0, fmt.Errorf("retiring unused collection collages: %w", err)
	}
	return int(tag.RowsAffected()), nil
}

// ReserveCollectionCollagePath queues a collage path in the artwork revision
// collector before a collage is built under it, pushing any earlier entry past
// the build. If the build fails or its node dies before SaveCollectionCollage,
// the collector deletes whatever it uploaded; a saved row releases the
// reservation. It reports held when a collector worker is processing the
// path, since it may be deleting objects the build would upload; the build
// must then wait for a later read.
func (r *LibraryCollectionRepository) ReserveCollectionCollagePath(ctx context.Context, path string) (held bool, err error) {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("beginning collection collage reservation: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	err = tx.QueryRow(ctx, `
		SELECT locked_at IS NOT NULL
		FROM artwork_revision_gc_candidates
		WHERE original_path = $1
		FOR UPDATE
	`, path).Scan(&held)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
	case err != nil:
		return false, fmt.Errorf("checking collection collage reservation: %w", err)
	case held:
		return true, nil
	}
	if _, err := tx.Exec(ctx, `SELECT public.queue_collection_poster_objects($1)`, path); err != nil {
		return false, fmt.Errorf("reserving collection collage path: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("committing collection collage reservation: %w", err)
	}
	return false, nil
}

// CollectionPosterWidths are the resized variants stored beside every
// original collection poster, uploaded or generated. The migration's
// queue_collection_poster_objects expands the same variants; change both
// together.
var CollectionPosterWidths = []int{500, 300}

func splitCollectionCollageRefs(refs []CollectionCollageRef) ([]string, []string) {
	ids := make([]string, len(refs))
	keys := make([]string, len(refs))
	for i, ref := range refs {
		ids[i] = ref.CollectionID
		keys[i] = ref.Key
	}
	return ids, keys
}

// CollectionPosters returns the poster each collection shows the viewer
// described by access, keyed by collection ID. An uploaded or template poster
// is the same for every viewer. Otherwise the poster is the collage of the
// first members the viewer can access. A collage not built yet is left out of
// this answer and built in the background, so a later read finds it.
// Collections listed from a query have no collage. Collections with no poster
// are absent.
func (s *LibraryCollectionService) CollectionPosters(ctx context.Context, collections []*models.LibraryCollection, access AccessFilter) map[string]CollectionPoster {
	posters := make(map[string]CollectionPoster, len(collections))
	var collageIDs []string
	for _, c := range collections {
		if c == nil {
			continue
		}
		if poster, ok := AssignedCollectionPoster(c); ok {
			posters[c.ID] = poster
			continue
		}
		if !collectionUsesLiveQuery(c) {
			collageIDs = append(collageIDs, c.ID)
		}
	}
	if len(collageIDs) == 0 || s == nil || s.collections == nil || s.CollageGen == nil {
		return posters
	}

	sources, err := s.collections.ListCollectionCollageSources(ctx, collageIDs, access)
	if err != nil {
		slog.WarnContext(ctx, "collage: failed to select collection collages", "component", "catalog", "error", err)
		return posters
	}
	refs := make([]CollectionCollageRef, 0, len(sources))
	for _, id := range collageIDs {
		if src := sources[id]; len(src) > 0 {
			refs = append(refs, CollectionCollageRef{CollectionID: id, Key: CollectionCollageKey(src)})
		}
	}
	stored, err := s.collections.GetCollectionCollages(ctx, refs)
	if err != nil {
		slog.WarnContext(ctx, "collage: failed to load collection collages", "component", "catalog", "error", err)
		return posters
	}

	var touch []CollectionCollageRef
	now := time.Now()
	for _, ref := range refs {
		c, ok := stored[ref]
		if !ok || c.Path == "" {
			s.buildCollageLater(ref, sources[ref.CollectionID])
			continue
		}
		posters[ref.CollectionID] = CollectionPoster{Path: c.Path, Thumbhash: c.Thumbhash, CollageKey: ref.Key}
		if now.Sub(c.LastUsedAt) > collectionCollageTouchInterval {
			touch = append(touch, ref)
		}
	}
	if err := s.collections.TouchCollectionCollages(ctx, touch); err != nil {
		slog.DebugContext(ctx, "collage: failed to touch collection collages", "component", "catalog", "error", err)
	}
	return posters
}

// CollectionCollage returns one stored collage. Image requests that name a
// collage directly, such as a Jellyfin image tag, use it.
func (s *LibraryCollectionService) CollectionCollage(ctx context.Context, collectionID, key string) (CollectionPoster, bool, error) {
	if s == nil || s.collections == nil {
		return CollectionPoster{}, false, nil
	}
	ref := CollectionCollageRef{CollectionID: collectionID, Key: key}
	stored, err := s.collections.GetCollectionCollages(ctx, []CollectionCollageRef{ref})
	if err != nil {
		return CollectionPoster{}, false, err
	}
	c, ok := stored[ref]
	if !ok || c.Path == "" {
		return CollectionPoster{}, false, nil
	}
	if time.Since(c.LastUsedAt) > collectionCollageTouchInterval {
		if err := s.collections.TouchCollectionCollages(ctx, []CollectionCollageRef{ref}); err != nil {
			slog.DebugContext(ctx, "collage: failed to touch collection collages", "component", "catalog", "error", err)
		}
	}
	return CollectionPoster{Path: c.Path, Thumbhash: c.Thumbhash, CollageKey: key}, true, nil
}

// PrepareCollectionCollage builds the collage the viewer described by access
// sees for the collection, unless it is already stored. It returns
// collage.ErrNotEnoughImages when that viewer can access no member with a
// poster.
func (s *LibraryCollectionService) PrepareCollectionCollage(ctx context.Context, collectionID string, access AccessFilter) error {
	if s.CollageGen == nil {
		return nil
	}
	sources, err := s.collections.ListCollectionCollageSources(ctx, []string{collectionID}, access)
	if err != nil {
		return err
	}
	src := sources[collectionID]
	if len(src) == 0 {
		return collage.ErrNotEnoughImages
	}
	ref := CollectionCollageRef{CollectionID: collectionID, Key: CollectionCollageKey(src)}
	stored, err := s.collections.GetCollectionCollages(ctx, []CollectionCollageRef{ref})
	if err != nil {
		return err
	}
	if c, ok := stored[ref]; ok && c.Path != "" {
		return nil
	}
	return s.buildCollage(ctx, ref, src)
}

// buildCollage composes and stores one collage, then retires the collection's
// collages that went unused. Nodes that build the same collage at once write
// the same objects, so the result doesn't depend on which one wins. The path
// stays reserved in the artwork revision collector until the row is saved, so
// a failed build leaves nothing behind.
func (s *LibraryCollectionService) buildCollage(ctx context.Context, ref CollectionCollageRef, sources []string) error {
	held, err := s.collections.ReserveCollectionCollagePath(ctx, s.CollageGen.CollectionCollagePath(ref.CollectionID, ref.Key))
	if err != nil {
		return err
	}
	if held {
		return ErrCollectionCollageBeingCollected
	}
	path, thumbhash, err := s.CollageGen.ComposeCollectionCollage(ctx, ref.CollectionID, ref.Key, sources)
	if err != nil {
		return err
	}
	c := CollectionCollage{CollectionCollageRef: ref, Path: path, Thumbhash: thumbhash}
	if err := s.collections.SaveCollectionCollage(ctx, c); err != nil {
		return err
	}

	if _, err := s.collections.RetireUnusedCollectionCollages(ctx, ref.CollectionID, time.Now().Add(-collectionCollageUnusedAfter)); err != nil {
		slog.WarnContext(ctx, "collage: failed to retire unused collages", "component", "catalog", "collection_id", ref.CollectionID, "error", err)
	}
	return nil
}

// collageBuildQueue runs the collage builds reads ask for in the background.
// It skips a collage already being built, bounds how many builds wait and
// run, and holds off retrying a collage whose build just failed. A build that
// dies with its node is retried by the next read on any node.
type collageBuildQueue struct {
	mu sync.Mutex
	// pending maps a collage to the time a read may ask for it again: zero
	// while a build runs, the retry time after one failed.
	pending map[CollectionCollageRef]time.Time
	slots   chan struct{}
}

func (s *LibraryCollectionService) collageQueue() *collageBuildQueue {
	s.collageBuildsOnce.Do(func() {
		s.collageBuilds = &collageBuildQueue{
			pending: make(map[CollectionCollageRef]time.Time),
			slots:   make(chan struct{}, collageBuildConcurrency),
		}
	})
	return s.collageBuilds
}

// claim reports whether a build of ref may start now and, if so, marks it
// running.
func (q *collageBuildQueue) claim(ref CollectionCollageRef, now time.Time) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	if retryAt, ok := q.pending[ref]; ok && (retryAt.IsZero() || now.Before(retryAt)) {
		return false
	}
	if len(q.pending) >= collageBuildMaxPending {
		for pendingRef, retryAt := range q.pending {
			if !retryAt.IsZero() && !now.Before(retryAt) {
				delete(q.pending, pendingRef)
			}
		}
		if len(q.pending) >= collageBuildMaxPending {
			return false
		}
	}
	q.pending[ref] = time.Time{}
	return true
}

func (q *collageBuildQueue) finish(ref CollectionCollageRef, failed bool, now time.Time) {
	q.mu.Lock()
	defer q.mu.Unlock()
	if failed {
		q.pending[ref] = now.Add(collageBuildRetryAfter)
		return
	}
	delete(q.pending, ref)
}

// buildCollageLater builds a collage a read found missing, off the request.
func (s *LibraryCollectionService) buildCollageLater(ref CollectionCollageRef, sources []string) {
	q := s.collageQueue()
	if !q.claim(ref, time.Now()) {
		return
	}
	go func() {
		failed := true
		defer func() {
			if r := recover(); r != nil {
				slog.Error("collage: build panic", "component", "catalog", "collection_id", ref.CollectionID, "panic", r, "stack", string(debug.Stack()))
			}
			q.finish(ref, failed, time.Now())
		}()
		q.slots <- struct{}{}
		defer func() { <-q.slots }()

		ctx, cancel := context.WithTimeout(context.Background(), collageBuildTimeout)
		defer cancel()
		err := s.buildCollage(ctx, ref, sources)
		switch {
		case err == nil:
			failed = false
		case errors.Is(err, collage.ErrNotEnoughImages):
			slog.DebugContext(ctx, "collage: no usable source images", "component", "catalog", "collection_id", ref.CollectionID)
		default:
			slog.WarnContext(ctx, "collage: background build failed", "component", "catalog", "collection_id", ref.CollectionID, "error", err)
		}
	}()
}
