package catalog

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/Silo-Server/silo-server/internal/access"
	"github.com/Silo-Server/silo-server/internal/models"
)

func TestCollectionCollageKeyNamesSourcesInOrder(t *testing.T) {
	key := CollectionCollageKey([]string{"a/poster/original.webp", "b/poster/original.webp"})
	if !regexp.MustCompile(`^[0-9a-f]{16}$`).MatchString(key) {
		t.Fatalf("key = %q, want 16 hex digits", key)
	}
	if again := CollectionCollageKey([]string{"a/poster/original.webp", "b/poster/original.webp"}); again != key {
		t.Fatalf("same sources gave %q then %q", key, again)
	}
	for name, sources := range map[string][]string{
		"reordered":    {"b/poster/original.webp", "a/poster/original.webp"},
		"fewer":        {"a/poster/original.webp"},
		"concatenated": {"a/poster/original.webpb/poster/original.webp"},
	} {
		if CollectionCollageKey(sources) == key {
			t.Fatalf("%s sources share the key %q", name, key)
		}
	}
}

func TestCollectionCollageSourcesSQLAppliesMemberAccess(t *testing.T) {
	sql, args := buildCollectionCollageSourcesSQL([]string{"c1"}, AccessFilter{
		AllowedLibraryIDs:  []int{1},
		DisabledLibraryIDs: []int{2},
		MaturityLimits:     access.MaturityLimits{MaxContentRating: "PG"},
	})
	for _, want := range []string{
		"mil.media_folder_id = ANY($3)",
		"NOT EXISTS (SELECT 1 FROM media_item_libraries mil WHERE mil.content_id = mi.content_id AND mil.media_folder_id = ANY($4))",
		"mi.content_rating_age <= $5",
		"mi.poster_path <> ''",
		"LIMIT $2",
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("collage source query lacks %q:\n%s", want, sql)
		}
	}
	if len(args) != 5 || args[1] != CollectionCollageSourceLimit {
		t.Fatalf("args = %v, want ids, limit, allowed, disabled, ceiling", args)
	}
}

func TestCollectionPostersWithoutCollagesServeAssignedPostersOnly(t *testing.T) {
	collections := []*models.LibraryCollection{
		{ID: "uploaded", PosterURL: "collection-images/uploaded/poster/original.1.webp", PosterThumbhash: "th"},
		{ID: "template", PosterURL: "/images/collection-templates/x.jpg", PosterFromTemplate: true},
		// The single shared collage older servers stored is never served.
		{ID: "legacy", PosterURL: "collection-images/legacy/poster/original.2.webp", PosterAutoGenerated: true},
		{ID: "none"},
	}
	for name, svc := range map[string]*LibraryCollectionService{
		"nil service":      nil,
		"no collage maker": {},
	} {
		posters := svc.CollectionPosters(context.Background(), collections, AccessFilter{})
		if len(posters) != 2 {
			t.Fatalf("%s: posters = %+v, want uploaded and template only", name, posters)
		}
		if got := posters["uploaded"]; got.Path != collections[0].PosterURL || got.Thumbhash != "th" || got.CollageKey != "" {
			t.Fatalf("%s: uploaded poster = %+v", name, got)
		}
		if _, ok := posters["legacy"]; ok {
			t.Fatalf("%s: legacy shared collage was served", name)
		}
	}
}

func TestCollageBuildQueueDedupesAndBacksOff(t *testing.T) {
	q := &collageBuildQueue{pending: map[CollectionCollageRef]time.Time{}, slots: make(chan struct{}, 1)}
	ref := CollectionCollageRef{CollectionID: "c1", Key: "k1"}
	now := time.Unix(1_000_000, 0)

	if !q.claim(ref, now) {
		t.Fatal("first claim refused")
	}
	if q.claim(ref, now) {
		t.Fatal("a running build was claimed twice")
	}
	q.finish(ref, true, now)
	if q.claim(ref, now.Add(collageBuildRetryAfter-time.Second)) {
		t.Fatal("a failed build was retried before its back-off ended")
	}
	if !q.claim(ref, now.Add(collageBuildRetryAfter)) {
		t.Fatal("a failed build was not retried after its back-off")
	}
	q.finish(ref, false, now)
	if _, ok := q.pending[ref]; ok {
		t.Fatal("a finished build stayed pending")
	}

	// A full queue refuses new builds, but expired back-offs make room.
	for i := range collageBuildMaxPending {
		q.pending[CollectionCollageRef{CollectionID: "busy", Key: fmt.Sprintf("k%d", i)}] = time.Time{}
	}
	if q.claim(CollectionCollageRef{CollectionID: "c2", Key: "k"}, now) {
		t.Fatal("a full queue accepted another build")
	}
	for r := range q.pending {
		q.pending[r] = now.Add(-time.Second)
		break
	}
	if !q.claim(CollectionCollageRef{CollectionID: "c2", Key: "k"}, now) {
		t.Fatal("an expired back-off did not make room")
	}
}
