package mediasample

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
)

// Excerpts of jellyfin-ffmpeg 7.1.4 listings.
const (
	filtersFixture = `Filters:
  T.. = Timeline support
  .S. = Slice threading
  ..C = Command support
  A = Audio input/output
  V = Video input/output
  N = Dynamic number and/or type of input/output
  | = Source or sink filter
 TSC aap               AA->A      Apply Affine Projection algorithm to first audio stream.
 ... silencedetect     A->A       Detect silence.
 ... blackframe        V->V       Detect frames that are (almost) black.
 T.. metadata          V->V       Manipulate video frame metadata.
 .S. signalstats       V->V       Generate statistics from video analysis.
 ... aevalsrc          |->A       Generate an audio signal generated by an expression.
 ... buffersink        V->|       Buffer video frames, and make them available to the end of the filter graph.
`
	muxersFixture = `Formats:
 D.. = Demuxing supported
 .E. = Muxing supported
 ..d = Is a device
 ---
  E  3g2             3GP2 (3GPP2 file format)
  E  chromaprint     Chromaprint
  Ed video4linux2,v4l2 Video4Linux2 output device
`
	chromaprintHelpFixture = `Muxer chromaprint [Chromaprint]:
    Default audio codec: pcm_s16le.
chromaprint muxer AVOptions:
  -silence_threshold <int>        E.......... threshold for detecting silence (from -1 to 32767) (default -1)
  -algorithm         <int>        E.......... version of the fingerprint algorithm (from 0 to INT_MAX) (default 1)
  -fp_format         <int>        E.......... fingerprint format to write (from 0 to 2) (default base64)
     raw             0            E.......... binary raw fingerprint
     compressed      1            E.......... binary compressed fingerprint
     base64          2            E.......... Base64 compressed fingerprint
`
	// concatCheckFixture is how jellyfin-ffmpeg 7.1.4 fails the concat check
	// after reading its list.
	concatCheckFixture = `[concat @ 0xfcc7c9ec0000] Impossible to open 'file:/nonexistent/silo-concat-check.mkv'
[in#0 @ 0xfcc7ca2e0200] Error opening input: No such file or directory
Error opening input file pipe:0.
Error opening input files: No such file or directory
`
	// concatUnknownKeywordFixture is how an ffmpeg that lacks a list
	// directive fails it.
	concatUnknownKeywordFixture = `[concat @ 0x7a82810000] Line 3: unknown keyword 'file_packet_meta'
[in#0 @ 0x7a83408000] Error opening input: Invalid data found when processing input
Error opening input file pipe:0.
Error opening input files: Invalid data found when processing input
`
)

// fakeListings answers listing commands from fixtures and counts them.
type fakeListings struct {
	calls   atomic.Int32
	filters string
	muxers  string
	help    string
	concat  string
	// concatList is the list the concat check wrote to stdin.
	concatList []byte
	err        error
	// block, when set, holds the filter listing until it is closed.
	block chan struct{}
}

func (f *fakeListings) list(_ context.Context, _ string, stdin []byte, args ...string) ([]byte, error) {
	f.calls.Add(1)
	if f.err != nil {
		return nil, f.err
	}
	switch strings.Join(args, " ") {
	case "-hide_banner -filters":
		if f.block != nil {
			<-f.block
		}
		return []byte(f.filters), nil
	case "-hide_banner -muxers":
		return []byte(f.muxers), nil
	case "-hide_banner -h muxer=chromaprint":
		return []byte(f.help), nil
	case "-hide_banner -nostdin -loglevel error -skip_frame:v nokey -protocol_whitelist file,pipe -f concat -safe 0 -i pipe:0 -f null -":
		f.concatList = stdin
		return []byte(f.concat), errors.New("exit status 254")
	}
	return nil, errors.New("unexpected listing " + strings.Join(args, " "))
}

func newFakeListings() *fakeListings {
	return &fakeListings{filters: filtersFixture, muxers: muxersFixture, help: chromaprintHelpFixture, concat: concatCheckFixture}
}

// useListings routes capability loads to f with an empty cache.
func useListings(t *testing.T, f *fakeListings) {
	t.Helper()
	capsCache.Lock()
	previous := capsCache.list
	capsCache.list = f.list
	capsCache.Unlock()
	InvalidateCapabilities()
	t.Cleanup(func() {
		capsCache.Lock()
		capsCache.list = previous
		capsCache.Unlock()
		InvalidateCapabilities()
	})
}

// fakeBinary writes a regular file whose identity the cache keys on.
func fakeBinary(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "ffmpeg")
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseListings(t *testing.T) {
	caps := Capabilities{filters: parseFilterList([]byte(filtersFixture)), muxers: parseMuxerList([]byte(muxersFixture))}
	for _, name := range []string{"aap", "silencedetect", "blackframe", "signalstats", "aevalsrc", "buffersink"} {
		if !caps.HasFilter(name) {
			t.Errorf("filter %q missing", name)
		}
	}
	for _, name := range []string{"=", "Timeline", "A", "|"} {
		if caps.HasFilter(name) {
			t.Errorf("legend word %q parsed as a filter", name)
		}
	}
	for _, name := range []string{"3g2", "chromaprint", "video4linux2", "v4l2"} {
		if !caps.HasMuxer(name) {
			t.Errorf("muxer %q missing", name)
		}
	}
	for _, name := range []string{"=", "D..", "Demuxing"} {
		if caps.HasMuxer(name) {
			t.Errorf("legend word %q parsed as a muxer", name)
		}
	}
}

func TestParseMuxerListOlderFormat(t *testing.T) {
	muxers := parseMuxerList([]byte("File formats:\n D. = Demuxing supported\n .E = Muxing supported\n --\n  E chromaprint     Chromaprint\n DE matroska,webm   Matroska\n D  aac             raw ADTS AAC\n"))
	caps := Capabilities{muxers: muxers}
	if !caps.HasMuxer("chromaprint") || !caps.HasMuxer("webm") || caps.HasMuxer("aac") {
		t.Fatalf("muxers %v", muxers)
	}
}

func TestRequire(t *testing.T) {
	fingerprint := Request{Audio: &AudioOutput{Fingerprint: true}}
	silence := Request{Audio: &AudioOutput{Silence: &SilenceParams{NoiseDB: -50, MinSeconds: 1}}}
	full := Capabilities{
		filters:        parseFilterList([]byte(filtersFixture)),
		muxers:         parseMuxerList([]byte(muxersFixture)),
		chromaprintRaw: true,
	}
	if err := full.Require(fingerprint); err != nil {
		t.Fatalf("fingerprint: %v", err)
	}
	if err := full.Require(silence); err != nil {
		t.Fatalf("silence: %v", err)
	}

	noRaw := full
	noRaw.chromaprintRaw = false
	if err := noRaw.Require(fingerprint); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), "raw fingerprint") {
		t.Fatalf("without raw output: %v", err)
	}
	if err := (Capabilities{}).Require(fingerprint); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), "chromaprint muxer") {
		t.Fatalf("without the muxer: %v", err)
	}
	if err := (Capabilities{}).Require(silence); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), "silencedetect") {
		t.Fatalf("without silencedetect: %v", err)
	}
	sampled := Request{Samples: &Samples{Seconds: []float64{1}}}
	if err := (Capabilities{}).Require(sampled); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), "sampled input list") {
		t.Fatalf("without sampled input lists: %v", err)
	}

	tail := Request{
		Audio: &AudioOutput{Fingerprint: true, Silence: &SilenceParams{NoiseDB: -50, MinSeconds: 0.5}},
		Stats: &StatsOutput{CropWidth: 0.9, CropHeight: 0.8, Width: 480, BlackThresholds: []int{20, 26, 32}},
	}
	if err := full.Require(tail); err != nil {
		t.Fatalf("tail pass: %v", err)
	}
	for _, missing := range []string{"blackframe", "signalstats", "metadata", "silencedetect"} {
		partial := full
		partial.filters = map[string]struct{}{}
		for name := range full.filters {
			if name != missing {
				partial.filters[name] = struct{}{}
			}
		}
		if err := partial.Require(tail); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), missing) {
			t.Fatalf("without %s: %v", missing, err)
		}
	}
	noMuxer := full
	noMuxer.muxers = nil
	if err := noMuxer.Require(tail); !errors.Is(err, ErrUnsupported) || !strings.Contains(err.Error(), "chromaprint muxer") {
		t.Fatalf("tail pass without the chromaprint muxer: %v", err)
	}
	tail.Audio.Fingerprint = false
	if err := noMuxer.Require(tail); err != nil {
		t.Fatalf("tail pass without a fingerprint needs no chromaprint: %v", err)
	}
}

func TestLoadCapabilitiesChecksChromaprintRawOutput(t *testing.T) {
	f := newFakeListings()
	f.help = "Muxer chromaprint [Chromaprint]:\n  -fp_format <int> (default base64)\n     base64 2\n"
	useListings(t, f)
	caps, err := LoadCapabilities(context.Background(), fakeBinary(t))
	if err != nil {
		t.Fatal(err)
	}
	if caps.chromaprintRaw {
		t.Fatal("chromaprint raw output reported without a raw fp_format")
	}
}

func TestLoadCapabilitiesSkipsChromaprintHelpWithoutTheMuxer(t *testing.T) {
	f := newFakeListings()
	f.muxers = "Formats:\n ---\n  E  matroska        Matroska\n"
	useListings(t, f)
	if _, err := LoadCapabilities(context.Background(), fakeBinary(t)); err != nil {
		t.Fatal(err)
	}
	if got := f.calls.Load(); got != 3 {
		t.Fatalf("%d listing commands, want filters, muxers, and the concat check only", got)
	}
}

func TestLoadCapabilitiesCachesPerBinaryIdentity(t *testing.T) {
	f := newFakeListings()
	useListings(t, f)
	binary := fakeBinary(t)

	for range 3 {
		caps, err := LoadCapabilities(context.Background(), binary)
		if err != nil {
			t.Fatal(err)
		}
		if caps.Require(Request{Audio: &AudioOutput{Fingerprint: true}}) != nil {
			t.Fatal("cached inventory lost chromaprint")
		}
	}
	if got := f.calls.Load(); got != 4 {
		t.Fatalf("%d listing commands after three loads, want one inventory (4 commands)", got)
	}

	// Replacing the binary in place changes its identity.
	if err := os.WriteFile(binary, []byte("#!/bin/sh\n# upgraded\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadCapabilities(context.Background(), binary); err != nil {
		t.Fatal(err)
	}
	if got := f.calls.Load(); got != 8 {
		t.Fatalf("%d listing commands after the binary changed, want a fresh inventory", got)
	}

	InvalidateCapabilities()
	if _, err := LoadCapabilities(context.Background(), binary); err != nil {
		t.Fatal(err)
	}
	if got := f.calls.Load(); got != 12 {
		t.Fatalf("%d listing commands after InvalidateCapabilities, want a fresh inventory", got)
	}
}

func TestLoadCapabilitiesDoesNotCacheFailures(t *testing.T) {
	f := newFakeListings()
	f.err = errors.New("exec format error")
	useListings(t, f)
	binary := fakeBinary(t)

	if _, err := LoadCapabilities(context.Background(), binary); err == nil {
		t.Fatal("LoadCapabilities succeeded while listings fail")
	} else if errors.Is(err, ErrUnsupported) {
		t.Fatalf("failed listing = %v, must not claim the binary lacks a capability", err)
	}
	f.err = nil
	caps, err := LoadCapabilities(context.Background(), binary)
	if err != nil {
		t.Fatalf("retry after a failure: %v", err)
	}
	if !caps.HasFilter("silencedetect") {
		t.Fatal("retry returned an empty inventory")
	}
}

func TestLoadCapabilitiesSharesOneLoadAcrossConcurrentCallers(t *testing.T) {
	f := newFakeListings()
	f.block = make(chan struct{})
	useListings(t, f)
	binary := fakeBinary(t)

	// A caller that gives up does not cancel the shared load.
	canceled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := LoadCapabilities(canceled, binary); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled caller: %v", err)
	}

	var wg sync.WaitGroup
	errs := make(chan error, 8)
	for range 8 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			caps, err := LoadCapabilities(context.Background(), binary)
			if err == nil && !caps.HasMuxer("chromaprint") {
				err = errors.New("empty inventory")
			}
			errs <- err
		}()
	}
	close(f.block)
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Fatal(err)
		}
	}
	if got := f.calls.Load(); got != 4 {
		t.Fatalf("%d listing commands for concurrent callers, want one inventory (4 commands)", got)
	}
}

// TestLoadCapabilitiesChecksConcatSamples offers Samples requests only to an
// ffmpeg that got through the whole list to opening its input.
func TestLoadCapabilitiesChecksConcatSamples(t *testing.T) {
	samples := Request{Samples: &Samples{Seconds: []float64{1}}, Stats: &StatsOutput{CropWidth: 1, CropHeight: 1, Width: 160}}
	for name, tt := range map[string]struct {
		output string
		want   bool
	}{
		"reads the list":        {concatCheckFixture, true},
		"lacks a directive":     {concatUnknownKeywordFixture, false},
		"lacks the demuxer":     {"Unknown input format: 'concat'\n", false},
		"blocks file protocols": {"[concat @ 0x1] Protocol 'file' not on whitelist 'pipe'!\n", false},
	} {
		t.Run(name, func(t *testing.T) {
			f := newFakeListings()
			f.concat = tt.output
			useListings(t, f)
			caps, err := LoadCapabilities(context.Background(), fakeBinary(t))
			if err != nil {
				t.Fatal(err)
			}
			if got := caps.Require(samples) == nil; got != tt.want {
				t.Fatalf("Require(samples) passed=%t, want %t", got, tt.want)
			}
			if !strings.Contains(string(f.concatList), "file_packet_meta sample 1\ninpoint 1\n") {
				t.Fatalf("concat check list %q does not use the Samples directives", f.concatList)
			}
		})
	}
}
